---
title: "The Fourish W's of Megan Church's Concert History"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    social: menu
    source_code: embed
    
    theme:
      version: 4
      primary: "#CCEDF9"
      navbar-bg: "#CCEDF9"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
---
 
<style type="text/css">
.chart-title {  /* chart_title  */
   font-size: 25px;
</style>

<style type="text/css">
.navbar-brand {  /* navbar_brand  */
   font-size: 35px;
</style>


```{r global, include=FALSE}

library(flexdashboard)

library (readr)
library(plotly)
library(tidyquant)
library(tidyverse)
library(dplyr)

### unfortunately, since I used data I collected about myself it is not available online
### don't forget to change the path name
data = read.csv('/Users/meganchurch/Library/CloudStorage/OneDrive-William&Mary/W&M/SeniorFall(2022)/data viz/FinalZip/Artists.csv')
```


Column {.tabset .tabset-fade data-width=150 data-height=1000}
-----------------------------------------------------------------------

### Headliners

```{r fig.width=5, fig.height=11, fig.no-padding, fig.keep='none' }

# filter out which category you want
filter = 'Headliners' 
ptree <- data %>% filter((Headliner == filter))

# get the count of each artist 
ptree <- ptree %>%
  count(Artist) 

# add a parent column 
ptree <- ptree %>%
  add_column(parent = filter)

# add parent rows 
ptree[nrow(ptree) + 1,] <- c(filter, '', '')
ptree[nrow(ptree) + 1,] <- c('AllArtists', '', 0)
    

## create the tree map    
ptree <- plot_ly(data = ptree) %>%
  add_trace(ptree, type="treemap",
          labels = ~Artist, #individual artists 
          parents = ~parent, #filter category
          values = ~n, #count of artists
          sort = TRUE, #if true sorts by count (largest on top) if false sorts alphabetically
          customdata = ~n, #for hover text input
  
          # set the color scale 
          marker = list(colorscale = list(c(0, '#FFC799'), list(1, '#FF9D4D')),
                                          cauto = T, #color based on values 
                                          cmin = -40, #upper bound of the color domain
                                          cmax = 40), #lower bound of the color domain
         
          pathbar = list(thickness = 23), #thickness of the path bar
          tiling = list(packing='dice-slice'), #how the rectangles are configured 
          
          # format the hover info
          hovertemplate = paste(
                "<b>%{customdata}</b>",
                "<extra></extra>"
            )
          )

## change the layout
ptree <- ptree %>% layout(
               uniformtext = list(minsize = 15, mode='show'), #make all the font size 15
               autosize = F, margin = list(
                                  l = 10, #left margin
                                  r = 10, #right margin
                                  b = 20, #bottom margin
                                  t = 20, #top margin
                                  pad = 4
                                  )
               )
ptree
```

### Openers

```{r fig.width=5, fig.height=11}
set.seed(2) #second tab in the tabset 

# filter out which category you want
filter = 'Openers' 
ptree1 <- data %>% filter((Headliner == filter))

# get the count of each artist 
ptree1 <- ptree1 %>%
  count(Artist) 

# add a parent column 
ptree1 <- ptree1 %>%
  add_column(parent = filter)

# add parent rows 
ptree1[nrow(ptree1) + 1,] <- c(filter, '', '')
ptree1[nrow(ptree1) + 1,] <- c('AllArtists', '', 0)
    
## create the tree map    
ptree1 <- plot_ly(data = ptree1) %>%
  add_trace(ptree1, type="treemap",
          labels = ~Artist, #individual artists 
          parents = ~parent, #filter category
          values = ~n, #count of artists
          sort = TRUE, #if true sorts by count (largest on top) if false sorts alphabetically
          customdata = ~n, #for hover text input

          # set the color scale
          marker = list(colorscale = list(c(0, '#99DCF3'), list(1, '#4DC1EA')),
                                          cauto = T, #color based on values 
                                          cmin = -40, #upper bound of the color domain
                                          cmax = 40), #lower bound of the color domain

          pathbar = list(thickness = 23), #thickness of the path bar
          tiling = list(packing='dice-slice'), #how the rectangles are configured 
          
          # format the hover info
          hovertemplate = paste(
                "<b>%{customdata}</b>",
                "<extra></extra>"
            )
          )

## change the layout
ptree1 <- ptree1 %>% layout(
               uniformtext = list(minsize = 15, mode='show'), #make all the font size 15
               autosize = F, margin = list(
                                  l = 10, #left margin
                                  r = 10, #right margin
                                  b = 20, #bottom margin
                                  t = 20, #top margin
                                  pad = 4
                                  )
               )
ptree1
```


Column {data-width=600}
-----------------------------------------------------------------------

### When?

```{r fig.height=1.7}

## create the tree map
ptime <- plot_ly(data = data, 
                 height = 175, 
                 type = 'scatter', mode = 'markers')%>%
  add_trace(data = data, x = ~Date, y = ~Headliner, customdata = ~Artist,
            transforms = list(
                                list(
                                  type = 'filter',
                                  target = 'y',
                                  operation = '=',
                                  value = 'Headliners'
                                )
                              ),
            
            marker = list(
                  color = 'rgba(255, 115, 0, 0.2)', #markers color - .2 opacity
                  size = 25, #marker size  
                  line = list(
                        color = 'rgb(255, 115, 0)', #marker outline color - full opacity
                        width = 2) # marker line width
                  ), 
            
            # format the hover info
            text = ~Artist,
            hovertemplate = paste(
                "<b>%{text}</b><br>",
                "%{x}",
                "<extra></extra>"
            )
          )%>%
  # set the range of dates 
  layout(showlegend = F, xaxis = list(range = c('2014-12-01', '2023-06-01')))

## change the layout 
ptime <- ptime %>%
  layout(
        font = list(size = 15), 
        
        # set x-axis attributes 
        xaxis = list(
                      title = " ", 
                      zerolinecolor = '#ffff',
                      zerolinewidth = 2, 
                      gridcolor = 'rgba(255, 115, 0, 0.2)'),
        
        # set y-axis attributes  
        yaxis = list(
                      title = " ", 
                      showticklabels = FALSE, 
                      zerolinecolor = 'rgb(255, 115, 0)',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
        
         # general attributes  
        plot_bgcolor='transparent', 
        autosize = F, margin = list(
                                  l = 20, #left margin 
                                  r = 20, #right margin
                                  b = 20, #bottom margin
                                  t = 20, #top margin
                                  pad = 4 
                                  )
         )

ptime
```

### Where?

```{r fig.height=4.5}

# set color variable 
colors = c('#FFA500', '#f98e00', '#f37200', '#EC5700')

## create map
map <- data 
map <- map %>%
  plot_ly(
    mode = 'scattermapbox', 
    size = 12, #marker size 
    color = ~Range1, colors = colors, #marker color
    opacity = .8, #marker opacity
    lat = ~Lat,
    lon = ~Long,
    text = ~Capacity,
    customdata = ~Venue,
    type = 'scattermapbox',
    
    # format the hover info
    hovertemplate = paste(
                "<b>%{customdata}</b><br>",
                "Capacity: %{text}",
                "<extra></extra>"
            )) 

## change layout
map <- map %>%
  layout(
    mapbox = list(
      style = "carto-positron", #map style
      zoom =1.5, #starting zoom
      center = list(lon = -40, lat = 45)), #starting center
      
      # set legend attributes
      legend = list(
                        title = list(
                                    text = "Venue Capacity"),
                        itemsizing ="constant", #make markers the same size 
                        itemclick = 'toggleothers', #click on legend to only view selected data
                        traceorder = 'normal', #order of legend items
                        x = 0, #legend position on x-axis
                        y = 1, #legend position on y-axis
                        font = list(size = 15), #font size
                        bgcolor = "white"), #background color
        
         
         # set hover attributes
         hoverlabel = list(font = list(size = 15)),
         
         # set general attributes
         font = list(size = 15),
         autosize = F, margin = list(
                                  l = 10, #left margin 
                                  r = 10, #right margin
                                  b = 20, #bottom margin
                                  t = 20, #top margin
                                  pad = 4 
                                  )
  )

map
```

### What?

```{r fig.height=3.7}

## reorganize the data by genre
pgenre <- data %>%
  mutate(Genre = as.factor(Genre), 
         Headliner = as.factor(Headliner)) %>% 
  
  # count to get the frequency table 
  count(Genre, Headliner) 

  # filter out headliners 
  pgenre_H <- pgenre %>% 
  filter(Headliner == 'Headliners')

  # filter out openers 
  pgenre_O <- pgenre %>% 
  filter(Headliner == 'Openers')

## create the bar chart 
pgenre <- plot_ly(y= ~Genre, 
          x= ~n, 
          data = pgenre_O, #plot the openers first since there are more of them 
          type = 'bar', 
          name = 'Openers',
          
          orientation = 'h', #make the bars horizontal
          height = 350,
          text = ~n, textposition = 'inside', #include count inside the bar 
          
          # set the color 
          marker = list(color = "rgba(0, 167, 225, 0.4)", #fill color - .4 opacity
                            line = list(color = "rgb(0, 167, 225)", #outline color - full opacity
                                        width = 1.5)), #outline width
           # format the hover info
          hovertemplate = paste(
                "<b>Openers</b><br>",
                "Genere: %{y}<br>",
                "Count: %{x}",
                "<extra></extra>"
            )
          )%>% 
  add_trace(y= ~Genre, 
          x= ~n, 
          data = pgenre_H, 
          type = 'bar',
          #color= ~Headliner,
          name = 'Headliners',
          
          orientation = 'h', #make the bars horizontal
          text = ~n, textposition = 'inside', #include count inside the bar 
          
          # set the color 
          marker = list(color = "rgba(255, 115, 0, 0.4)", #fill color - .4 opacity
                            line = list(color = "rgb(255, 115, 0)", #outline color - full opacity
                                        width = 1.5)), #outline width

          # format the hover info
          hovertemplate = paste(
                "<b>Headliners</b><br>",
                "Genere: %{y}<br>",
                "Count: %{x}",
                "<extra></extra>"
            ))

## change the layout 
pgenre <- pgenre %>%
  layout(
         barmode="stack", #stacked bar chart
         
         # set x-axis attributes
         xaxis = list(
                      title = " ",
                      showticklabels = FALSE,
                      zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         
         # set y-axis attributes
         yaxis = list(
                      title = " ",
                      categoryorder = "total ascending",
                      zerolinecolor = 'rgb(233,29,99)',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         
         # set legend attributes
         legend = list(itemclick = 'toggleothers', #click on legend to only view selected data
                       traceorder = 'normal', #order of legend items
                       x = .4, #legend position on x-axis
                       y = .2, #legend position on y-axis
                       font = list(size = 15)), 
         
         
         # set hover attributes
         hoverlabel = list(font = list(size = 15)),
         
         # set general attributes
         plot_bgcolor='transparent',
         font = list(size = 15),
         autosize = F, margin = list(
                                      l = 10, #left margin
                                      r = 10, #right margin
                                      b = 20, #bottom margin
                                      t = 20, #top margin
                                      pad = 4
                                    )
         )
pgenre
```

